_target_: datamodule.trajdata_datamodule.TrajdataDataModule

train_args:
  - data: [lyft_train]
  - data_dir: {'lyft_train': 'datasets/lyft/scenes/train.zarr'}
  - dt: 0.5
  - history: [2., 2.]
  - future: [6., 6.]
  - ego_only: True
  - bs: ${batch_size}
val_args:
  - data: [nusc_trainval-train_val]
  - data_dir: {'nusc_trainval': 'datasets/nuScenes'}
  - dt: 0.5
  - history: [2., 2.]
  - future: [6., 6.]
  - ego_only: True
  - bs: ${batch_size}
test_args:
  - data: [nusc_trainval-val]
  - data_dir: {'nusc_trainval': 'datasets/nuScenes'}
  - dt: 0.5
  - history: [2., 2.]
  - future: [6., 6.]
  - ego_only: True
  - bs: ${batch_size}
shuffle: True
augmentations: null
num_workers: ${num_workers}
pin_memory: True
test: ${test}