_target_: datamodule.trajdata_datamodule.TrajdataDataModule

train_args:
  - data: [nusc_trainval-train]
  - data_dir: {'nusc_trainval': 'datasets/nuScenes'}
  - dt: 0.1
  - history: [0.9, 0.9]
  - future: [3., 3.]
  - ego_only: True
  - bs: ${batch_size}
val_args:
  - data: [nusc_trainval-train_val]
  - data_dir: {'nusc_trainval': 'datasets/nuScenes'}
  - dt: 0.1
  - history: [0.9, 0.9]
  - future: [3., 3.]
  - ego_only: True
  - bs: ${batch_size}
test_args:
  - data: [nusc_trainval-val]
  - data_dir: {'nusc_trainval': 'datasets/nuScenes'}
  - dt: 0.1
  - history: [0.9, 0.9]
  - future: [3., 3.]
  - ego_only: True
  - bs: ${batch_size}
shuffle: True
augmentations: null
num_workers: ${num_workers}
pin_memory: True
test: ${test}
